### ISSUE TITLE
`format-prompt` not defined in Emacs 27

### ISSUE THREAD

**Issue by phikal** [astoff/buffer-env#12]
Hi,

you use the function `format-prompt`, even though "Package-Requires" indicates that Emacs 27.1 is the minimal version.  It seems nonsensical to me to raise the version just because of one function (27.1 is probably still the most widely used version). The simplest solution in this case would be to replace it with equivalent, backwards compatible code.  An alternative would be to use the [compat](https://elpa.gnu.org/packages/compat.html) library, if you intend to make use of other functionality that is defined in Emacs 28.1+ in the future.

**Comment by astoff** [comment]
So this means that (without compat) we would have to hardcode the customizable option that Emacs now has in `minibuffer-default-prompt-format`?

**Comment by astoff** [comment]
This is an old thread, but I'm using compat now in this package.
