### ISSUE TITLE
Support pyproject.toml

### ISSUE THREAD

**Issue by astoff** [astoff/buffer-env#13]
For Python projects using a a fully featured project manager like Poetry, Hatch or PDM, it would be nice to extract the project environment directly from the corresponding `pyproject.toml` file.

The following code, which can be pasted in the user configuration, seems to work but need more testing. Feedback is welcome!

```elisp
(setq buffer-env-script-name '(".envrc" "pyproject.toml"))
(with-eval-after-load 'buffer-env
  (add-to-list 'buffer-env-commands
               '("pyproject.toml" . "\
BACKEND=$(sed -nr 's/^build-backend\s*=\s*\"([a-z]+).*/\\1/p' \"$0\")
case $BACKEND in
  poetry|pdm) $BACKEND run env -0;;
  hatchling) hatch run env -0;;
  *) echo >&2 \"Unsupported build backend '$BACKEND'.\" && exit 1;;
esac")))
```

**Comment by quotuva** [comment]
Test data point: Works on Poetry in my system.
