### ISSUE TITLE
`cl-letf` warning

### ISSUE THREAD

**Issue by manuel-uberti** [astoff/buffer-env#15]
Hi Augusto,

this is just a minor thing, maybe something you are already aware of, but if I use the snippet in the README to set up the buffer-local process environment, I get a warning. Namely, this:

```emacs-lisp
(defun buffer-env-inherit (fn &rest args)
  "Call FN with ARGS using the buffer-local process environment.
Intended as an advice around commands that start a process after
switching buffers."
  (cl-letf (((default-value 'process-environment) process-environment)
            ((default-value 'exec-path) exec-path))
    (apply fn args)))
```

Results in the following message when Flymake is active:
```
‘((default-value 'process-environment) process-environment)’ is a malformed function
```

The message disappears if I place this at the beginning of my `init.el`:

```emacs-lisp
(eval-when-compile
  (require 'cl-lib))
```

Also, I've started to notice this message recently, but I wasn't able to pin down the exact Emacs master commit that triggers it. As of now, I am using Emacs built on [`3425690`](https://github.com/emacs-mirror/emacs/commit/34256906aa885d8929f17ab08b0748586b05ef06) commit if it helps.

**Comment by astoff** [comment]
Well, this is confusing. If the macro is autoloaded (as emacs -Q tells me it is), then we shouldn't need the require, right? If this changed recently, it's bound to break other things as well...

**Comment by astoff** [comment]
> Do you want me to file a bug on the Emacs tracker referencing this ticket?

Probably. I did some tests locally. If I evaluate say
```
(cl-letf (((default-value 'process-environment) nil)))
```
on a fresh emacs -Q, then I get an error the first time, and then in a second attempt it works — probably because cl-lib got loaded in the process of displaying the error message. So maybe the reason why you started to get this error is because you removed something from your config that used to load cl-lib as a side-effect?
