### ISSUE TITLE
Temporarily disable hack-local-variables-hook? And misc org-babel issues.

### ISSUE THREAD

**Issue by dcunited001** [astoff/buffer-env#16]
Here's my config:

```emacs-lisp
(setup (:pkg buffer-env)
  (:option buffer-env-script-name "manifest.scm")
  (add-hook 'comint-mode-hook #'hack-dir-local-variables-non-file-buffer)
  (add-hook 'hack-local-variables-hook #'buffer-env-update))
```

However, inside the file I'm editing, `hack-local-variables-hook` is set to `(outline-apply-default-state t)`.

I'm editing an org-file that tangles the `manifest.scm`, but even as I'm editing the babel block that produces the file, it is attempting to run a bad manifest. For now, I'm just going to output to manifest2.scm and delete the manifest.

I've tried the following from within the org bufffer.

```emacs-lisp
(setq hack-locals-old hack-local-variables-hook)
(setq hack-local-variables-hook nil)
```

Is there any way to temporarily disable this within a buffer/project?

**Comment by dcunited001** [comment]
Also, in buffers where `buffer-env` is active, there are some variables which I want to be global to emacs which end up out of sync. 

I use these scripts to set `SSH_AUTH_SOCK` and `SSH_AGENT_PID` in emacs:

+ [emacs-agent-set](https://github.com/dcunited001/ellipsis/blob/master/.bin/emacs-agent-set) 
+ [emacs-agent-clear](https://github.com/dcunited001/ellipsis/blob/master/.bin/emacs-agent-clear)

Do you know how to walk through the environments and set an environment variable like this across emacs?

**Comment by dcunited001** [comment]
And one more related problem: in this org file [UTIL.org](https://github.com/ectorepo/ectorepo/blob/master/UTIL.org), I'm trying to set the environment variable `PYTHONPATH` to make accessible the python modules from the guix package `git-repo`.

Most everything works, but when I try to run the last python block, the environment loaded shows os.environ["PATH"] correctly, but sys.path is not correct. When I run `guix shell -m` and `python3` in the terminal, i get a python that behaves as expected.  Am I doing something wrong here? 

I'll dig around in the `buffer-env` source a bit soon, but if you could elucidate some of this, that would really help. Thanks.

**Comment by astoff** [comment]
I'm only superficially  familiar with org-babel, but it seems like you want to set `buffer-env-script-name` to nil in the tangled buffer. I will not add special support for org-babel, but if you can describe a general mechanism that helps you, I can implement it.

As to the other scripts, maybe calling `setenv` in a temp buffer (which has no local binding of `process-environment`) would do the trick for you.

**Comment by dcunited001** [comment]
Thanks for the help. I'll try that out. I'm still learning how to organize `guix.scm` and `manifest.scm` into projects.
