### ISSUE TITLE
How to inherit environment from manifest.scm to external applications

### ISSUE THREAD

**Issue by rezahousseini** [astoff/buffer-env#23]
When editing org documents I sometimes run python code in a python interpreter:

- First I open the code editor in a source block `C-c '`
- then I start python console `C-c C-p`
- then I send the code to the interpreter `C-c C-C`

contrary to only running `C-c C-c` inside the source block this does not inherit the buffer environment. Is there a way to achieve this (easily)?

Another issue I stumbled onto was running the export command asynchronously

- Open export menu `C-c C-e`
- select async `C-a`
- select en export option e.g. latex `l o`

this fails due to missing dependencies. Is there a possible workaround using buffer-env?

**Comment by astoff** [comment]
For the Python shell, adding `(add-hook 'comint-mode-hook #'buffer-env-update)` to your config should solve it.
