### ISSUE TITLE
Saving buffer-env-safe-files: wrong-type-argument listp t

### ISSUE THREAD

**Issue by manuel-uberti** [astoff/buffer-env#4]
Hi,

I edited the `.envrc` of one of my projects today and run `direnv allow` to make sure the changes are loaded. 

However, the first time I act on this project (e.g., `C-x p p` -> Select project -> `RET` -> `v` (for VC-Dir)), I get the following prompt:

```
Mark current version of ‘/home/manuel/code/eerlijewoz/cockpit/.envrc’ as safe to execute? (y or n)
```

And when I hit `y` I get:

```
Debugger entered--Lisp error: (wrong-type-argument listp t)
  custom-save-variables()
  custom-save-all()
  customize-save-variable(buffer-env-safe-files (("/home/manuel/code/eerlijewoz/cockpit/.envrc" . "ffe8ad77e9d2affb4445c4a83d830d4606860e1d5ba86aab99...")))
  buffer-env--authorize("/home/manuel/code/eerlijewoz/cockpit/.envrc")
  buffer-env-update()
  hack-local-variables-apply()
  hack-dir-local-variables-non-file-buffer()
  project--value-in-dir(project-vc-merge-submodules "~/code/eerlijewoz/cockpit/")
  project--vc-merge-submodules-p("~/code/eerlijewoz/cockpit/")
  project-try-vc("~/code/eerlijewoz/cockpit/")
  project--find-in-directory("~/code/eerlijewoz/cockpit/")
  project-current(t)
  project-find-file(nil)
  funcall-interactively(project-find-file nil)
  project-switch-project("~/code/eerlijewoz/cockpit/")
  funcall-interactively(project-switch-project "~/code/eerlijewoz/cockpit/")
  command-execute(project-switch-project)
```

This is how I set up `buffer-env` in my `init.el`:
```emacs-lisp
(add-hook 'hack-local-variables-hook #'buffer-env-update)
(with-eval-after-load 'buffer-env
  (push '(".envrc" . "direnv exec . env -0") buffer-env-commands))

(defun mu-buffer-env-inherit (fn &rest args)
  "Call FN with ARGS using the buffer-local process environment."
  (cl-letf (((default-value 'process-environment) process-environment)
            ((default-value 'exec-path) exec-path))
    (apply fn args)))
(advice-add #'mu-buffer-env-inherit :around #'project-shell)
(advice-add #'mu-buffer-env-inherit :around #'shell)
```

**Comment by manuel-uberti** [comment]
FTR, I am using GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2022-04-20, built om commit `ebde448a14d44719b78b8b873a88448b73d72572`.

**Comment by manuel-uberti** [comment]
To give you a minimal reproducible recipe:
- M-x shell
- mkdir test-envrc
- cd test-envrc
- `C-x C-f` .envrc
- write `export TEST="test1"`
- `C-x C-s` and `C-x k`
- git init
- direnv allow
- `C-x p f`
- You'll see the above mentioned prompt. Hit `y` to see the error

**Comment by manuel-uberti** [comment]
Upon further debugging, I found that `(secure-hash 'sha256 (current-buffer))` in `buffer-env--authorize` was generating a hash value different from what I previously had in my `custom.el` file. Which I think makes sense since the content of `.envrc` are changed.

To workaround this problem (basically to avoid the prompt), I replaced the hash in `custom.el` for my `.envrc` entry with the new one I get in the Backtrace, and the problem seems to be "solved".

I am pretty sure this is not the correct approach, though. :)

**Comment by astoff** [comment]
Yes, when some script changes, I should just ask again for authorization.

As to the "forget authorization" command, something on those lines should be added. My original plan was to add a "garbage collect" command to remove all old hashes. Do you think there's a need for this more fine-grained version that allows to forget about a specific hash?

**Comment by astoff** [comment]
> If the point is just to ensure [persist](https://elpa.gnu.org/packages/persist.html)ence, but the user isn't expected to manually interact with the value

That's correct.

> then something else might be better. E.g. to use a dependency like persist.

I'm open to being convinced of why something else might be better. My two cents so far:
* Saving and reading from a file is probably 5 lines of code, so I wouldn't mind doing it manually.
* Custom is already used to persist variables like `custom-safe-themes` and `safe-local-variable-values`. So this seems to be the status quo anyway.

**Comment by astoff** [comment]
> To give you a minimal reproducible recipe

I tried this and I get no errors.

> To workaround this problem (basically to avoid the prompt), I replaced the hash in `custom.el` for my `.envrc` entry with the new one I get in the Backtrace, and the problem seems to be "solved".
> 
> I am pretty sure this is not the correct approach, though. :)

Looking at the implementation of `buffer-env--authorize`, there should be no difference if the file was previously unknown or was known with a different hash: the case `(member (cons file hash) buffer-env-safe-files)` of a certain `or` form will fail.

This makes me think the problem lies somewhere else, possibly in your own configuration?

**Comment by astoff** [comment]
> Another point is that for systems like Guix, a seperate file like ~/.config/guix/shell-authorized-directories may be used to manage authorized directories. Should buffer-env complement this or check if Guix is fine with a file?

(Sorry for not replying earlier to this comment.) I'm not a fan of integrating too deeply with any particular external tool, since there's probably at least half a dozen of them out there. As an advanced user, you could add the code you pasted here as a `:before-until` advice to `buffer-env--authorize`, and I think that's sufficient configurability for the time being.
