### ISSUE TITLE
Adding buffer-env-update to hack-local-variables-hook does not affect buffers without files

### ISSUE THREAD

**Issue by phikal** [astoff/buffer-env#8]
The recommended configuration says to add `buffer-env-update` to `hack-local-variables-hook`, but this only works for buffers with an associated file.  In all other cases nothing happens, which is confusing and breaks the transparency that I think would be desirable. 

This can be remedied by ensuring that `hack-dir-local-variables-non-file-buffer` is called, e.g. by adding

    (add-hook 'comint-mode-hook #'hack-dir-local-variables-non-file-buffer)

or 

    (add-hook 'comint-mode-hook #'buffer-env-update)

to the user configuration, e.g. if you want buffer-env to work in a shell or REPL.  But this approach requires manually supporting every non-file major-mode.

Assuming I didn't make some mistake here, do you see any good way around this.  If not, I think adding a minor mode that initializes buffer-env would be useful?

**Comment by astoff** [comment]
> I think adding a minor mode that initializes buffer-env?

This is the approach of the [envrc](https://github.com/purcell/envrc) package, and it still has some related issues which are described in its Readme and in the [inheritenv](https://github.com/purcell/inheritenv) package. So it seems there's no good general solution for this problem?

Incidentally, I like the transparency that the special process-environment applies if and only if other dir-locals apply, whatever the criterion is for the latter. Also note that if you are already using direnv or some other shell hook to manage project environments, then you probably _don't_ want buffer-env to mess with the environment of shell buffers, especially if you use `M-x shell` as opposed to `M-x project-shell`.

With that said, I like your suggestion to add `buffer-env-update` to the comint hook. This seems to solve the "env inheritance" issue for a large class of cases, with small caveats. I'd say the right approach here is to suggest it in the Readme, discussing the pros and cons.

**Comment by astoff** [comment]
Everything I've observed is explained (albeit tersely) in https://github.com/astoff/buffer-env#compatibility-issues.

**Comment by astoff** [comment]
@phikal Looking again at this, I'm wondering why would anyone not want comint-mode to call `hack-dir-local-variables-non-file-buffer` by default. Do you think this is an Emacs bug?

**Comment by phikal** [comment]
I don't have a good explanation for why this isn't the case, so it might well be a bug.

**Comment by astoff** [comment]
Okay. In any case now I recommend in the Readme what you suggested in the original message — not sure why I didn't do it immediately.

> But this approach requires manually supporting every non-file major-mode.

Any other that bother you? It seems the non-file modes are more or less consistent in calling `hack-dir-local-variables-non-file-buffer`.
